### ISSUE TITLE
Split repo

### ISSUE THREAD

**Issue by jotapea** [CNTRPRTY/xcpdev-genesis#17]
@JavierCervilla @Chriton @DerpHerpenstein @mkeresty 

I'm thinking about splitting this one repo into:
- **[CNTRPRTY/xcpdev-genesis](https://github.com/CNTRPRTY/xcpdev-genesis)**: This repo reverted to commit https://github.com/CNTRPRTY/xcpdev-genesis/commit/0ffba5d2c7df514757b0a4032c89fc57b1cc7977. Will live in its own subdomain \<TBD>.xcp.dev. The current minimalist version of the website (and backend), which I like, and want to keep up.
- **[CNTRPRTY/xcpdev-spa](https://github.com/CNTRPRTY/xcpdev-spa)**: Will become the (*)next default www.xcp.dev frontend. Builds upon the genesis single page application, currently undergoing a community-led redesign.
- **[CNTRPRTY/xcpdev-api](https://github.com/CNTRPRTY/xcpdev-api)**: Builds upon the [/server/express_server](https://github.com/CNTRPRTY/xcpdev-genesis/tree/main/server/express_server), including community-led openapi auto docs and the (**e**)xchain api "replacement".

Then, [CNTRPRTY/xcpdev](https://github.com/CNTRPRTY/xcpdev) will become a hub linking to all of the above...

And the (*)future: https://github.com/CNTRPRTY/xcpdev-ssr, ...

If anyone has some issue with this approach, please reply to discuss asap. If no resistance is met, I will proceed with the changes tomorrow Jan 15.

**Comment by JavierCervilla** [comment]
Is cool to have it divided, I would explore the possibility of having also a xcpdev next Js versión or deno fresh to have a full serverside versión, but I full support the split into his own repo

**Comment by jotapea** [comment]
@JavierCervilla That conversation can start happening at https://github.com/CNTRPRTY/xcpdev-ssr.

**Comment by Chriton** [comment]
Yes, I agree to the following:
- CNTRPRTY/xcpdev-genesis - can be reverted to the commit you said
- CNTRPRTY/xcpdev-spa - should have the current state of the xcpdev repo - excluding the "server" folder.
- CNTRPRTY/xcpdev-api - should have just the content of the "server" folder from the xcpdev repo

There also was a CNTRPRTY/xcpdev-next repo there - @jotapea  did you delete it? 
This should be an empty one to make the nextJS version.

**Comment by Chriton** [comment]
Another thing to point out is that having them in separate repos will make it easier later to containerize each of them.
So basically make docker images for each and use them in a docker stack for example with docker-compose and also  integrate them in things like getumbrel and run it on a raspberryPi.

**Comment by jotapea** [comment]
Split completed. Continue working in your new branches instead of genesis, which will be reverted soon.

**Comment by Chriton** [comment]
> Split completed. Continue working in your new branches instead of genesis, which will be reverted soon.

Ok, thanks, will continue on the spa one.

P.S You mean repos, not new branches.
