### ISSUE TITLE
Public api

### ISSUE THREAD

**Issue by Jpja** [CNTRPRTY/xcpdev-genesis#2]
Is there a public api or plans to make one?

**Comment by jotapea** [comment]
At the moment, [this comment](https://github.com/CNTRPRTY/xcpdev/issues/1#issuecomment-1465477764) explains why a public api has not been a focus for [xcp.dev](https://xcp.dev).

But I'm keeping this issue open to have a place to discuss it, measure the demand for it, and decide if/when to release it.

**Comment by jotapea** [comment]
The website's api has been formalized, and it was designed to be consumed by anyone. Particularly by having an open CORS header that allows any origin (for now at least).

So, basically the web app is just another consumer of this api. See: https://www.xcp.dev/api

Closing.
