### ISSUE TITLE
View asset by longname

### ISSUE THREAD

**Issue by Jpja** [CNTRPRTY/xcpdev-genesis#4]
https://www.xcp.dev/asset/JOURNEYPAINT.HELLO.0M shows error message 'asset not found'.

 'JOURNEYPAINT.HELLO.0M' is the longname for asset 'A505430575883775048':
 https://www.xcp.dev/asset/A505430575883775048
 
 Would be nice to have URL with longname forward to the numeric asset.

**Comment by jotapea** [comment]
Will look into it!
